# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '029bae3d-77df-41ed-8cd2-8b4bc401d389'
  imageRepository: 'img-madefy'
  containerRegistry: 'labdockermadefy.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker_config_files/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
- task: BatchScript@1
  inputs:
    filename: '../*sh'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Pago pelo Uso(1)(93a1f09a-933e-4e26-996c-4c542b1a16c5)'
    azureContainerRegistry: '{"loginServer":"labdockermadefy.azurecr.io", "id" : "/subscriptions/93a1f09a-933e-4e26-996c-4c542b1a16c5/resourceGroups/lab-paulo/providers/Microsoft.ContainerRegistry/registries/labdockermadefy"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
    includeSourceTags: true
    includeLatestTag: true